// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Click event for processing
type ClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referrer      string                 `protobuf:"bytes,5,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	DeviceType    string                 `protobuf:"bytes,8,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Browser       string                 `protobuf:"bytes,9,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string                 `protobuf:"bytes,10,opt,name=os,proto3" json:"os,omitempty"`
	Timestamp     int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IsUnique      bool                   `protobuf:"varint,13,opt,name=is_unique,json=isUnique,proto3" json:"is_unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *ClickEvent) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *ClickEvent) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ClickEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ClickEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ClickEvent) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *ClickEvent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ClickEvent) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ClickEvent) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *ClickEvent) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *ClickEvent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ClickEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClickEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClickEvent) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

// Response for click processing
type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request for URL statistics
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Granularity   string                 `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"` // hour, day, week, month
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *StatsRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *StatsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StatsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *StatsRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

// URL statistics response
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	TotalClicks   int64                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueClicks  int64                  `protobuf:"varint,3,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	TimeSeries    []*TimeSeriesPoint     `protobuf:"bytes,4,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	CountryStats  []*CountryStats        `protobuf:"bytes,5,rep,name=country_stats,json=countryStats,proto3" json:"country_stats,omitempty"`
	DeviceStats   []*DeviceStats         `protobuf:"bytes,6,rep,name=device_stats,json=deviceStats,proto3" json:"device_stats,omitempty"`
	BrowserStats  []*BrowserStats        `protobuf:"bytes,7,rep,name=browser_stats,json=browserStats,proto3" json:"browser_stats,omitempty"`
	ReferrerStats []*ReferrerStats       `protobuf:"bytes,8,rep,name=referrer_stats,json=referrerStats,proto3" json:"referrer_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *StatsResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *StatsResponse) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *StatsResponse) GetTimeSeries() []*TimeSeriesPoint {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

func (x *StatsResponse) GetCountryStats() []*CountryStats {
	if x != nil {
		return x.CountryStats
	}
	return nil
}

func (x *StatsResponse) GetDeviceStats() []*DeviceStats {
	if x != nil {
		return x.DeviceStats
	}
	return nil
}

func (x *StatsResponse) GetBrowserStats() []*BrowserStats {
	if x != nil {
		return x.BrowserStats
	}
	return nil
}

func (x *StatsResponse) GetReferrerStats() []*ReferrerStats {
	if x != nil {
		return x.ReferrerStats
	}
	return nil
}

// Time series data point
type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	UniqueClicks  int64                  `protobuf:"varint,3,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSeriesPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeSeriesPoint) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *TimeSeriesPoint) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

// Country statistics
type CountryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryStats) Reset() {
	*x = CountryStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryStats) ProtoMessage() {}

func (x *CountryStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryStats.ProtoReflect.Descriptor instead.
func (*CountryStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *CountryStats) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CountryStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *CountryStats) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Device statistics
type DeviceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceType    string                 `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStats) Reset() {
	*x = DeviceStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStats) ProtoMessage() {}

func (x *DeviceStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStats.ProtoReflect.Descriptor instead.
func (*DeviceStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceStats) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *DeviceStats) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Browser statistics
type BrowserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Browser       string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserStats) Reset() {
	*x = BrowserStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserStats) ProtoMessage() {}

func (x *BrowserStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserStats.ProtoReflect.Descriptor instead.
func (*BrowserStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *BrowserStats) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *BrowserStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *BrowserStats) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Referrer statistics
type ReferrerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrer      string                 `protobuf:"bytes,1,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferrerStats) Reset() {
	*x = ReferrerStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrerStats) ProtoMessage() {}

func (x *ReferrerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferrerStats.ProtoReflect.Descriptor instead.
func (*ReferrerStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *ReferrerStats) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *ReferrerStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *ReferrerStats) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Request for top URLs
type TopURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // clicks, unique_clicks, created_at
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopURLsRequest) Reset() {
	*x = TopURLsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopURLsRequest) ProtoMessage() {}

func (x *TopURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopURLsRequest.ProtoReflect.Descriptor instead.
func (*TopURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *TopURLsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TopURLsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TopURLsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TopURLsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

// Top URLs response
type TopURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URLMetrics          `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopURLsResponse) Reset() {
	*x = TopURLsResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopURLsResponse) ProtoMessage() {}

func (x *TopURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopURLsResponse.ProtoReflect.Descriptor instead.
func (*TopURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *TopURLsResponse) GetUrls() []*URLMetrics {
	if x != nil {
		return x.Urls
	}
	return nil
}

// URL metrics
type URLMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	TotalClicks   int64                  `protobuf:"varint,3,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueClicks  int64                  `protobuf:"varint,4,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastClicked   int64                  `protobuf:"varint,6,opt,name=last_clicked,json=lastClicked,proto3" json:"last_clicked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLMetrics) Reset() {
	*x = URLMetrics{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLMetrics) ProtoMessage() {}

func (x *URLMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLMetrics.ProtoReflect.Descriptor instead.
func (*URLMetrics) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *URLMetrics) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *URLMetrics) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *URLMetrics) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *URLMetrics) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *URLMetrics) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *URLMetrics) GetLastClicked() int64 {
	if x != nil {
		return x.LastClicked
	}
	return 0
}

// Request for dashboard data
type DashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardRequest) Reset() {
	*x = DashboardRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRequest) ProtoMessage() {}

func (x *DashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRequest.ProtoReflect.Descriptor instead.
func (*DashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *DashboardRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *DashboardRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// Dashboard response
type DashboardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalUrls       int64                  `protobuf:"varint,1,opt,name=totalUrls,proto3" json:"totalUrls,omitempty"`
	TotalClicks     int64                  `protobuf:"varint,2,opt,name=totalClicks,proto3" json:"totalClicks,omitempty"`
	UniqueClicks    int64                  `protobuf:"varint,3,opt,name=uniqueClicks,proto3" json:"uniqueClicks,omitempty"`
	ActiveUrls      int64                  `protobuf:"varint,4,opt,name=activeUrls,proto3" json:"activeUrls,omitempty"`
	ClickTimeline   []*TimeSeriesPoint     `protobuf:"bytes,5,rep,name=clickTimeline,proto3" json:"clickTimeline,omitempty"`
	TopUrls         []*URLMetrics          `protobuf:"bytes,6,rep,name=topUrls,proto3" json:"topUrls,omitempty"`
	TopCountries    []*CountryStats        `protobuf:"bytes,7,rep,name=topCountries,proto3" json:"topCountries,omitempty"`
	DeviceBreakdown []*DeviceStats         `protobuf:"bytes,8,rep,name=deviceBreakdown,proto3" json:"deviceBreakdown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *DashboardResponse) GetTotalUrls() int64 {
	if x != nil {
		return x.TotalUrls
	}
	return 0
}

func (x *DashboardResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *DashboardResponse) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *DashboardResponse) GetActiveUrls() int64 {
	if x != nil {
		return x.ActiveUrls
	}
	return 0
}

func (x *DashboardResponse) GetClickTimeline() []*TimeSeriesPoint {
	if x != nil {
		return x.ClickTimeline
	}
	return nil
}

func (x *DashboardResponse) GetTopUrls() []*URLMetrics {
	if x != nil {
		return x.TopUrls
	}
	return nil
}

func (x *DashboardResponse) GetTopCountries() []*CountryStats {
	if x != nil {
		return x.TopCountries
	}
	return nil
}

func (x *DashboardResponse) GetDeviceBreakdown() []*DeviceStats {
	if x != nil {
		return x.DeviceBreakdown
	}
	return nil
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{14}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/analytics/analytics.proto\x12\tanalytics\"\xf1\x02\n" +
	"\n" +
	"ClickEvent\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1a\n" +
	"\breferrer\x18\x05 \x01(\tR\breferrer\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1f\n" +
	"\vdevice_type\x18\b \x01(\tR\n" +
	"deviceType\x12\x18\n" +
	"\abrowser\x18\t \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\n" +
	" \x01(\tR\x02os\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12\x1b\n" +
	"\tis_unique\x18\r \x01(\bR\bisUnique\"A\n" +
	"\x0fProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x89\x01\n" +
	"\fStatsRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12 \n" +
	"\vgranularity\x18\x04 \x01(\tR\vgranularity\"\xab\x03\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x03R\vtotalClicks\x12#\n" +
	"\runique_clicks\x18\x03 \x01(\x03R\funiqueClicks\x12;\n" +
	"\vtime_series\x18\x04 \x03(\v2\x1a.analytics.TimeSeriesPointR\n" +
	"timeSeries\x12<\n" +
	"\rcountry_stats\x18\x05 \x03(\v2\x17.analytics.CountryStatsR\fcountryStats\x129\n" +
	"\fdevice_stats\x18\x06 \x03(\v2\x16.analytics.DeviceStatsR\vdeviceStats\x12<\n" +
	"\rbrowser_stats\x18\a \x03(\v2\x17.analytics.BrowserStatsR\fbrowserStats\x12?\n" +
	"\x0ereferrer_stats\x18\b \x03(\v2\x18.analytics.ReferrerStatsR\rreferrerStats\"l\n" +
	"\x0fTimeSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12#\n" +
	"\runique_clicks\x18\x03 \x01(\x03R\funiqueClicks\"`\n" +
	"\fCountryStats\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\"f\n" +
	"\vDeviceStats\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\"`\n" +
	"\fBrowserStats\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\"c\n" +
	"\rReferrerStats\x12\x1a\n" +
	"\breferrer\x18\x01 \x01(\tR\breferrer\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\"y\n" +
	"\x0eTopURLsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\"<\n" +
	"\x0fTopURLsResponse\x12)\n" +
	"\x04urls\x18\x01 \x03(\v2\x15.analytics.URLMetricsR\x04urls\"\xd0\x01\n" +
	"\n" +
	"URLMetrics\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\x12!\n" +
	"\ftotal_clicks\x18\x03 \x01(\x03R\vtotalClicks\x12#\n" +
	"\runique_clicks\x18\x04 \x01(\x03R\funiqueClicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12!\n" +
	"\flast_clicked\x18\x06 \x01(\x03R\vlastClicked\"L\n" +
	"\x10DashboardRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\x89\x03\n" +
	"\x11DashboardResponse\x12\x1c\n" +
	"\ttotalUrls\x18\x01 \x01(\x03R\ttotalUrls\x12 \n" +
	"\vtotalClicks\x18\x02 \x01(\x03R\vtotalClicks\x12\"\n" +
	"\funiqueClicks\x18\x03 \x01(\x03R\funiqueClicks\x12\x1e\n" +
	"\n" +
	"activeUrls\x18\x04 \x01(\x03R\n" +
	"activeUrls\x12@\n" +
	"\rclickTimeline\x18\x05 \x03(\v2\x1a.analytics.TimeSeriesPointR\rclickTimeline\x12/\n" +
	"\atopUrls\x18\x06 \x03(\v2\x15.analytics.URLMetricsR\atopUrls\x12;\n" +
	"\ftopCountries\x18\a \x03(\v2\x17.analytics.CountryStatsR\ftopCountries\x12@\n" +
	"\x0fdeviceBreakdown\x18\b \x03(\v2\x16.analytics.DeviceStatsR\x0fdeviceBreakdown\"\x0f\n" +
	"\rHealthRequest\"z\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\xe6\x02\n" +
	"\x10AnalyticsService\x12A\n" +
	"\fProcessClick\x12\x15.analytics.ClickEvent\x1a\x1a.analytics.ProcessResponse\x12@\n" +
	"\vGetURLStats\x12\x17.analytics.StatsRequest\x1a\x18.analytics.StatsResponse\x12C\n" +
	"\n" +
	"GetTopURLs\x12\x19.analytics.TopURLsRequest\x1a\x1a.analytics.TopURLsResponse\x12I\n" +
	"\fGetDashboard\x12\x1b.analytics.DashboardRequest\x1a\x1c.analytics.DashboardResponse\x12=\n" +
	"\x06Health\x12\x18.analytics.HealthRequest\x1a\x19.analytics.HealthResponseB<Z:github.com/go-systems-lab/go-url-shortener/proto/analyticsb\x06proto3"

var (
	file_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_analytics_proto_rawDescData []byte
)

func file_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_analytics_proto_rawDescData
}

var file_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_analytics_analytics_proto_goTypes = []any{
	(*ClickEvent)(nil),        // 0: analytics.ClickEvent
	(*ProcessResponse)(nil),   // 1: analytics.ProcessResponse
	(*StatsRequest)(nil),      // 2: analytics.StatsRequest
	(*StatsResponse)(nil),     // 3: analytics.StatsResponse
	(*TimeSeriesPoint)(nil),   // 4: analytics.TimeSeriesPoint
	(*CountryStats)(nil),      // 5: analytics.CountryStats
	(*DeviceStats)(nil),       // 6: analytics.DeviceStats
	(*BrowserStats)(nil),      // 7: analytics.BrowserStats
	(*ReferrerStats)(nil),     // 8: analytics.ReferrerStats
	(*TopURLsRequest)(nil),    // 9: analytics.TopURLsRequest
	(*TopURLsResponse)(nil),   // 10: analytics.TopURLsResponse
	(*URLMetrics)(nil),        // 11: analytics.URLMetrics
	(*DashboardRequest)(nil),  // 12: analytics.DashboardRequest
	(*DashboardResponse)(nil), // 13: analytics.DashboardResponse
	(*HealthRequest)(nil),     // 14: analytics.HealthRequest
	(*HealthResponse)(nil),    // 15: analytics.HealthResponse
}
var file_proto_analytics_analytics_proto_depIdxs = []int32{
	4,  // 0: analytics.StatsResponse.time_series:type_name -> analytics.TimeSeriesPoint
	5,  // 1: analytics.StatsResponse.country_stats:type_name -> analytics.CountryStats
	6,  // 2: analytics.StatsResponse.device_stats:type_name -> analytics.DeviceStats
	7,  // 3: analytics.StatsResponse.browser_stats:type_name -> analytics.BrowserStats
	8,  // 4: analytics.StatsResponse.referrer_stats:type_name -> analytics.ReferrerStats
	11, // 5: analytics.TopURLsResponse.urls:type_name -> analytics.URLMetrics
	4,  // 6: analytics.DashboardResponse.clickTimeline:type_name -> analytics.TimeSeriesPoint
	11, // 7: analytics.DashboardResponse.topUrls:type_name -> analytics.URLMetrics
	5,  // 8: analytics.DashboardResponse.topCountries:type_name -> analytics.CountryStats
	6,  // 9: analytics.DashboardResponse.deviceBreakdown:type_name -> analytics.DeviceStats
	0,  // 10: analytics.AnalyticsService.ProcessClick:input_type -> analytics.ClickEvent
	2,  // 11: analytics.AnalyticsService.GetURLStats:input_type -> analytics.StatsRequest
	9,  // 12: analytics.AnalyticsService.GetTopURLs:input_type -> analytics.TopURLsRequest
	12, // 13: analytics.AnalyticsService.GetDashboard:input_type -> analytics.DashboardRequest
	14, // 14: analytics.AnalyticsService.Health:input_type -> analytics.HealthRequest
	1,  // 15: analytics.AnalyticsService.ProcessClick:output_type -> analytics.ProcessResponse
	3,  // 16: analytics.AnalyticsService.GetURLStats:output_type -> analytics.StatsResponse
	10, // 17: analytics.AnalyticsService.GetTopURLs:output_type -> analytics.TopURLsResponse
	13, // 18: analytics.AnalyticsService.GetDashboard:output_type -> analytics.DashboardResponse
	15, // 19: analytics.AnalyticsService.Health:output_type -> analytics.HealthResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_analytics_analytics_proto_init() }
func file_proto_analytics_analytics_proto_init() {
	if File_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_analytics_proto = out.File
	file_proto_analytics_analytics_proto_goTypes = nil
	file_proto_analytics_analytics_proto_depIdxs = nil
}
